[package]
name = "ranpaman-core"
version = "0.1.0"
authors = ["Tomasz Sus"]
edition = "2018"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.1"
zeroize = "0.9"
rust-argon2 = "0.4"
orion = "0.14"
num-bigint = "0.2"
num-traits = "0.2"
blake2 = "0.8"